version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
        logging:
            options:
                max-size: 10m
                max-file: "3"
    webserver:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: dbt_dags
        restart: always
        depends_on:
            - postgres
        environment:
            - INITIAL_USER=admin
            - INITIAL_PASSWORD=admin
            - INITIAL_EMAIL=admin
            - INITIAL_FIRSTNAME=admin
            - INITIAL_LASTNAME=admin
            - AIRFLOW__CORE__LOAD_EXAMPLES=false
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - AIRFLOW_VAR_ENVIRONMENT=local
            - DBT_HOST=DBT_HOST
            - DBT_PORT=5432
            - DBT_USER=DBT_USER
            - DBT_ENV_SECRET_PASSWORD=DBT_ENV_SECRET_PASSWORD
            - DBT_DBNAME=DBT_DBNAME
            - DBT_SCHEMA=DBT_SCHEMA
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/opt/airflow/dags
            - ./dbt:/opt/airflow/dbt
            - ./tests:/opt/airflow/tests
            - ./.sqlfluff:/opt/airflow/.sqlfluff
            - ./.sqlfluffignore:/opt/airflow/.sqlfluffignore
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3